name: CodeQuality Dynamic Code Analysis Valgrind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: make -C 3_Implementation/ test
<<<<<<< HEAD
    - name: Valgrind
      run: valgrind ./3_Implementation/build/test_TIC.out.out
=======
    - name: Valgrid
      run: valgrind ./3_Implementation/build/Tic-TAC-TOE.out.out
>>>>>>> 45c8e8b8adfd658a85ad87dbc1097af2b71aff21



   

