name: CodeQuality Dynamic Code Analysis Valgrind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: make -C 3_Implementation/ test
    - name: Valgrid
<<<<<<< HEAD
      run: valgrind ./3_Implementation/build/Tic-TAC-TOE.out
=======
      run: valgrind ./3_Implementation/build/Test_Tic-TAC-TOE.out
>>>>>>> 7eacdb0848f55d6f8a6258ef31426203f1a87352


   

